# Default values for data-pipeline

# Namespace
namespace: data-pipeline

# Storage class
storageClass: standard

# ==================== MINIO ====================
minio:
  enabled: true
  image:
    repository: minio/minio
    tag: latest
    pullPolicy: IfNotPresent
  
  credentials:
    rootUser: minio_access_key
    rootPassword: minio_secret_key
  
  buckets:
    - bronze
    - silver
    - gold
    - mlflow-artifacts
  
  persistence:
    size: 1Gi
  
  service:
    type: ClusterIP
    apiPort: 9000
    consolePort: 9001
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# ==================== POSTGRES (Data Source) ====================
postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  
  credentials:
    user: postgres
    password: postgres
    database: data_source
  
  walLevel: logical
  
  persistence:
    size: 5Gi
  
  service:
    type: ClusterIP
    port: 5432
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# ==================== AIRFLOW ====================
airflow:
  enabled: true
  serviceAccount:
    name: airflow
    
  image:
    repository: remmydream/airflow-image
    tag: "v1.0"
    pullPolicy: IfNotPresent
  
  admin:
    username: admin
    password: admin
    firstname: Admin
    lastname: User  
    email: admin@example.com
  
  config:
    executor: LocalExecutor
    secretKey: this_is_a_very_secured_key
    sparkConnection: "spark://spark-master:7077?deploy_mode=cluster"
  
  postgres:
    user: airflow
    password: airflow
    database: airflow
    persistence:
      size: 5Gi
  
  webserver:
    replicas: 1
    service:
      type: ClusterIP
      port: 8080
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  
  scheduler:
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  
  persistence:
    dagsSize: 2Gi
    logsSize: 2Gi 

# ==================== MLFLOW ====================
mlflow:
  enabled: true
  
  image:
    repository: remmydream/mlflow-image
    tag: "v1.0"
    pullPolicy: IfNotPresent
  
  replicas: 1
  
  service:
    type: ClusterIP
    host: "0.0.0.0"
    port: 5000

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "3Gi"
  
  # Backend Store Database (PostgreSQL)
  postgres:
    user: mlflow
    password: mlflow
    db: mlflow
    replicas: 1
    persistence:
      enabled: true
      size: 5Gi
      storageClass: ""
      accessMode: ReadWriteOnce
  
  # Artifact Store (S3/MinIO)
  s3:
    bucket: mlflow-artifacts

# ==================== FASTAPI ====================
fastapi:
  enabled: true
  
  app:
    image:
      repository: remmydream/fastapi-image
      tag: "v1.0"
      pullPolicy: IfNotPresent
    
    # Number of replicas
    replicas: 1
    
    reload: true
    
    healthCheck:
      path: /health
    
    # Service configuration
    service:
      type: ClusterIP
      port: 8000
    
    # Resource limits
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  
  gitSync:
    enabled: true
    image:
      repository: registry.k8s.io/git-sync/git-sync
      tag: v4.2.4
      pullPolicy: IfNotPresent
    
    repo: https://github.com/RemMyDream/DQOPs
    branch: backend
    depth: 1  
    wait: 60 
    
    subPath: ""
    
    root: /git
    
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  
  persistence:
    codeSize: 2Gi  # Size for PVC storing code
  
  # Internal PostgreSQL Database
  postgres:
    user: postgres
    password: postgres
    database: internal_database
    
    persistence:
      size: 5Gi
    
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
