services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=password123
      - CLICKHOUSE_DB=warehouse
    ports:
      - "8123:8123"
      - "9002:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - data-pipeline

volumes:
  clickhouse_data:

networks:
  data-pipeline:
    external: true