services:
  spark-master:
    container_name: spark-master
    build: .
    image: spark-image:latest
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s 
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - ../data_quality:/opt/spark/data_quality
      - spark-logs:/opt/spark/spark-events
      - ../utils:/opt/spark/utils
      - ../backend:/opt/spark/backend
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'
    networks:
      - default
      - spark_network

  spark-history-server:
    container_name: spark-history
    image: spark-image:latest
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      spark-master:
        condition: service_healthy
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - ../data_quality:/opt/spark/data_quality
      - spark-logs:/opt/spark/spark-events
      - ../utils:/opt/spark/utils
      - ../backend:/opt/spark/backend
    ports:
      - '18080:18080'
    networks:
      - default
      - spark_network

  spark-worker:
    image: spark-image:latest
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      spark-master:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
      - ../data_quality:/opt/spark/data_quality
      - ../utils:/opt/spark/utils
      - ../backend:/opt/spark/backend
    networks:
      - default
      - spark_network

volumes:
  spark-logs:
networks:
  default:
    name: bigdata-net
    external: True
  spark_network:
    driver: bridge