apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingestion-dag-airflow-pvc
  namespace: dqops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingestion-dags-pvc
  namespace: dqops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingestion-tmp-pvc
  namespace: dqops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  namespace: dqops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: docker.getcollate.io/openmetadata/ingestion:1.11.0
        envFrom:
        - configMapRef:
            name: ingestion-config
        # CHANGED: 'entrypoint' becomes 'command', 'command' becomes 'args'
        command: ["/bin/bash"]
        args:
        - "/opt/airflow/ingestion_dependency.sh"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dag-airflow
          mountPath: /opt/airflow/dag_generated_configs
        - name: dags
          mountPath: /opt/airflow/dags
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: dag-airflow
        persistentVolumeClaim:
          claimName: ingestion-dag-airflow-pvc
      - name: dags
        persistentVolumeClaim:
          claimName: ingestion-dags-pvc
      - name: tmp
        persistentVolumeClaim:
          claimName: ingestion-tmp-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion
  namespace: dqops
spec:
  selector:
    app: ingestion
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
