apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dqops
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: sourcedb
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-metadata-secret
  namespace: dqops
type: Opaque
stringData:
  POSTGRES_USER: openmetadata_user
  POSTGRES_PASSWORD: openmetadata_password
  POSTGRES_DB: openmetadata_db
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: dqops
type: Opaque
stringData:
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: dqops
type: Opaque
stringData:
  POSTGRES_PASSWORD: airflow
  WEBSERVER_SECRET_KEY: this_is_a_very_secured_key
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dqops
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: clickhouse-secret
#   namespace: dqops
# type: Opaque
# stringData:
#   CLICKHOUSE_PASSWORD: ""
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: superset-secret
#   namespace: dqops
# type: Opaque
# stringData:
#   ADMIN_PASSWORD: admin

