apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dqops
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: sourcedb
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-metadata-secret
  namespace: dqops
type: Opaque
stringData:
  POSTGRES_USER: openmetadata_user
  POSTGRES_PASSWORD: openmetadata_password
  POSTGRES_DB: openmetadata_db
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: dqops
type: Opaque
stringData:
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: password

