apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse-01:8123
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse-01
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: ""
    isDefault: true