app:
  name: "Data Quality Management"
  version: "1.0.0"
  debug: false
  host: "0.0.0.0"
  port: 8000

spark:
  master: spark://spark-master:7077
  app: dqops

data_source: 
  host: data_source
  port: 5432
  
lakehouse:
  endpoint: minio:9000
  root_user: minio_access_key
  root_password: minio_secret_key
  secure: false

kafka:
  brokers: "kafka-node-1:9092,kafka-node-1:9092,kafka-node-2:9092,kafka-node-3:9092,kafka-node-4:9092"
  topic: "event_streaming"

internal_database:
  username: postgres
  password: postgres
  database: internal_database
  host: internal_database
  port: 5432

airflow:
  username: admin
  password: admin
  url: http://webserver:8080