services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-01/var/log/clickhouse-server:/var/log/clickhouse-server
      - ${PWD}/fs/volumes/clickhouse-01/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    networks:
      - data-pipeline
  clickhouse-02:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse-02
    hostname: clickhouse-02
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-02/var/log/clickhouse-server:/var/log/clickhouse-server
    ports:
      - "127.0.0.1:8124:8123"
      - "127.0.0.1:9001:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    networks:
      - data-pipeline
  clickhouse-03:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse-03
    hostname: clickhouse-03
    ports:
      - "127.0.0.1:8125:8123"
      - "127.0.0.1:9002:9000"
    volumes:
      - ${PWD}/fs/volumes/clickhouse-03/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-03/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-03/var/log/clickhouse-server:/var/log/clickhouse-server
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    networks:
      - data-pipeline

  clickhouse-04:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse-04
    hostname: clickhouse-04
    volumes:
      - ${PWD}/fs/volumes/clickhouse-04/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-04/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-04/var/log/clickhouse-server:/var/log/clickhouse-server
    ports:
      - "127.0.0.1:8126:8123"
      - "127.0.0.1:9003:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    networks:
      - data-pipeline

  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:latest-alpine"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/log/clickhouse-keeper:/var/log/clickhouse-keeper
    ports:
      - "127.0.0.1:9181:9181"
      - "127.0.0.1:9234:9234"  
    networks:
      - data-pipeline

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:latest-alpine"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/log/clickhouse-keeper:/var/log/clickhouse-keeper
    ports:
      - "127.0.0.1:9182:9181"
      - "127.0.0.1:9235:9234"
    networks:
      - data-pipeline

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:latest-alpine"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/log/clickhouse-keeper:/var/log/clickhouse-keeper
    ports:
      - "127.0.0.1:9183:9181"
      - "127.0.0.1:9236:9234" 
    networks:
      - data-pipeline
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ${PWD}/fs/volumes/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - data-pipeline

networks:
  data-pipeline:
    name: data-pipeline
    external: true